Add JSON_LENGTH for MySQL
beberlei/DoctrineExtensions pull request #356
Opened 2020-10-02 17:40 UTC by MrMitch

This adds support for the `JSON_LENGTH` function for MySQL.

https://dev.mysql.com/doc/refman/8.0/en/json-attribute-functions.html#function_json-length

2020-10-03 05:50 UTC, stevelacey commented on src/Query/Mysql/JsonLength.php
> +        return sprintf('JSON_LENGTH(%s, %s)', $target, $path);
```suggestion
        if ($path) {
            return sprintf('JSON_LENGTH(%s, %s)', $target, $path);
        }
        
        return sprintf('JSON_LENGTH(%s)', $target);
```

2020-10-03 05:50 UTC, stevelacey commented on tests/Query/Mysql/JsonLengthTest.php
> +            "SELECT JSON_LENGTH('{}', '$') AS sclr_0 FROM Blank b0_"
```suggestion
            "SELECT JSON_LENGTH('{}') from DoctrineExtensions\Tests\Entities\Blank as blank",
            "SELECT JSON_LENGTH('{}') AS sclr_0 FROM Blank b0_"
```

2020-10-03 05:51 UTC, stevelacey commented on src/Query/Mysql/JsonLength.php
> +            $this->path = '$';
```suggestion
```

2020-10-03 05:52 UTC, stevelacey requested changes
Thanks for your contribution. I think when it's possible to mirror the SQL to the DQL exactly we probably should, see above amends.

2020-10-03 13:53 UTC, MrMitch commented
Hi @stevelacey, thank you for your feedback. I've rebased the branch on master (since #355 was merged) and applied the changes you proposed (with a slight variation to prevent an error in `SqlWalker::walkStringPrimary` if `$path` is null).

2020-11-02 10:57 UTC, merged

2020-11-02 10:58 UTC, stevelacey commented
@MrMitch thanks!